version: '3.1'

services:
  reconwithme-stage:
    container_name: nftsoul-staging
    hostname: nftsoul-staging
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - IMG=16.17-alpine3.15
        - LOCATION=nftsoul-staging
    restart: always
    user: root:root
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - COMPOSE_PROJECT_NAME=nftsoul-staging
    ports:
      - ${PORT}:${PORT}