name: Production Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          passphrase: ${{ secrets.passphrase }}
          key: ${{ secrets.privateKey }}
          port: ${{ secrets.port }}
          script: sudo sh deploy-scripts/deploy-production.sh
